### ISSUE TITLE
Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by merhovon** [Qengineering/Install-OpenCV-Jetson-Nano#11]
I have performed the following steps as described and now receive an error message:

# a fresh start, so check for updates
$ sudo apt-get update
$ sudo apt-get upgrade
# install nano
$ sudo apt-get install nano
# install dphys-swapfile
$ sudo apt-get install dphys-swapfile
# enlarge the boundary (4.5.2 and higher)
$ sudo nano /sbin/dphys-swapfile
# give the required memory size
$ sudo nano /etc/dphys-swapfile
# reboot afterwards
$ sudo reboot

# check your memory first
$ free -m
# you need at least a total of 8.5 GB!
# if not, enlarge your swap space as explained in the guide
$ wget https://github.com/Qengineering/Install-OpenCV-Jetson-Nano/raw/main/OpenCV-4-7-0.sh
$ sudo chmod 755 ./OpenCV-4-7-0.sh
$ ./OpenCV-4-7-0.sh

[CMakeError.log](https://github.com/Qengineering/Install-OpenCV-Jetson-Nano/files/10514606/CMakeError.log)
[CMakeOutput.log](https://github.com/Qengineering/Install-OpenCV-Jetson-Nano/files/10514607/CMakeOutput.log)

**Comment by Qengineering** [comment]
Dear @merhovon ,

Check with the command `$ free -m` your memory spacce and swap size.
If you have 2 GByte of RAM instead of 4, or for some other reason has a shortage of memory, enlarge the swap space extra.

**Comment by merhovon** [comment]
The command free -m prints the following:
![Screenshot from 2023-01-27 20-55-51](https://user-images.githubusercontent.com/26201870/215185256-53bf37a5-f6ed-4aa6-bc22-a4a537975271.png)

Which makes me wonder why I still have so little swap space. I have actually increased this according to the instructions:

![Screenshot from 2023-01-27 20-57-30](https://user-images.githubusercontent.com/26201870/215185754-3aad2624-78ea-43fe-b0f2-e1c0fc292e45.png)
![Screenshot from 2023-01-27 20-58-00](https://user-images.githubusercontent.com/26201870/215185756-f5fcdfac-dfc3-45ab-bf36-766c93bbb052.png)


Here are the steps I took to do this:
# a fresh start, so check for updates
$ sudo apt-get update
$ sudo apt-get upgrade
# install nano
$ sudo apt-get install nano
# install dphys-swapfile
$ sudo apt-get install dphys-swapfile
# enlarge the boundary (4.5.2 and higher)
$ sudo nano /sbin/dphys-swapfile
# give the required memory size
$ sudo nano /etc/dphys-swapfile
# reboot afterwards
$ sudo reboot

**Comment by Qengineering** [comment]
You must have the size of the required swap space also available on your SD-card.
When you only have 3 GB free on your SD-card, you can only allocate 3 GB of swap space.
Thereby, you need extra space for all the generated OpenCV files. In practice 16 GB free space will give 8 GB of swap space and enough for the compilation of OpenCV

**Comment by merhovon** [comment]
I still have 40GB free on my memory card.
![Screenshot from 2023-01-27 21-39-49](https://user-images.githubusercontent.com/26201870/215192731-2d9bb36a-4b47-4651-a009-ea3429104e28.png)

**Comment by Qengineering** [comment]
I see you still have commented line `CONF_SWAPSIZE=8192` in `/etc/dphys-swapfile`.
If you remove the hashtag (#) in front of the line, it will solve your problem.
