### ISSUE TITLE
CV installation.'.format(fnames)) ImportError: OpenCV loader: missing configuration file: ['config-3.6.py', 'config-3.py']. Check OpenCV installation.

### ISSUE THREAD

**Issue by arielkantorovich** [Qengineering/Install-OpenCV-Jetson-Nano#16]
Hi, 
I using OpenCv-4-8-0 on my jetson nano.
It's look like the install sucssed, When I look on JTop I see YES on opencv4.8.0 .
but, when I try import opencv I get this error 
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/uvision/VitTracker/lib/python3.6/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/uvision/VitTracker/lib/python3.6/site-packages/cv2/__init__.py", line 115, in bootstrap
    ], True)
  File "/home/uvision/VitTracker/lib/python3.6/site-packages/cv2/__init__.py", line 109, in load_first_config
    raise ImportError('OpenCV loader: missing configuration file: {}. Check OpenCV installation.'.format(fnames))
ImportError: OpenCV loader: missing configuration file: ['config-3.6.py', 'config-3.py']. Check OpenCV installation.
`
When I run python from directory `/usr/lib/python3.6/dist-packages/cv2/python-3.6`
I sussed  but then opencv is in version 4.1.1.
I don't understand what I miss, I will happy to any help.

**Comment by Qengineering** [comment]
Not sure what you are doing. You don't need to run opencv from the `/usr/lib/python3.6/dist-packages/cv2/python-3.6` folder.
After the installation just run it like the screen dump below.
![image](https://github.com/Qengineering/Install-OpenCV-Jetson-Nano/assets/44409029/28f4fb87-3500-4ed5-aa11-1bf9ed4273ea)

**Comment by arielkantorovich** [comment]
I know, but when I try to import opencv I get this error.
Maybe there is a connection to venv?
because after I compile opencv I try open new venv with python 3.6.9 and pip3 install /path_to_build_folder/python_loader I see in pip3 list opencv 4.8.0 but again when I try import cv2 I get:
`Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/home/uvision/VitTracker/lib/python3.6/site-packages/cv2/__init__.py", line 181, in <module> bootstrap() File "/home/uvision/VitTracker/lib/python3.6/site-packages/cv2/__init__.py", line 115, in bootstrap ], True) File "/home/uvision/VitTracker/lib/python3.6/site-packages/cv2/__init__.py", line 109, in load_first_config raise ImportError('OpenCV loader: missing configuration file: {}. Check OpenCV installation.'.format(fnames)) ImportError: OpenCV loader: missing configuration file: ['config-3.6.py', 'config-3.py']. Check OpenCV installation`

**Comment by Qengineering** [comment]
I think you have to install OpenCV in your virtual environment.
At the moment your installation is system-wide.

**Comment by arielkantorovich** [comment]
It does not make sense every time that I want to open a new project with Venv I need to compile opencv again?
I compile opencv from source code why I can not install from pip?
If I remember when I install from your script I was connected to venv project and still get same problem

**Comment by arielkantorovich** [comment]
I install opencv where I connected to my venv,

**Comment by Qengineering** [comment]
When creating your virtual environment, please add --system-site-packages in the command.
![Screenshot from 2023-11-16 13-10-27](https://github.com/Qengineering/Install-OpenCV-Jetson-Nano/assets/44409029/ba88154a-0f60-4eb8-a495-20a090ed0092)

**Comment by arielkantorovich** [comment]
I install opencv again not from your script using your guida and it's work with pip3 install /bath to build/python_loader.
still thank you for your help.
