### ISSUE TITLE
About mega

### ISSUE THREAD

**Issue by HrakDovlatyan** [Qengineering/Install-OpenCV-Jetson-Nano#2]
Can't download the image file the limit is 3gb. Is there any other sites where I can download it?

**Comment by Qengineering** [comment]
Dear @HrakDovlatyan ,

I'm going to transfer a copy to Google Drive. Please be patient, the download and upload will take some time. I'll send you a link when I'm done.

**Comment by HrakDovlatyan** [comment]
ok, thank you

**Comment by Qengineering** [comment]
Dear @HrakDovlatyan,

Please try Gdrive [link](https://drive.google.com/file/d/1yTT1jc533KXBCRFpduaOmj-xV6YujzAU/view?usp=sharing)
