### ISSUE TITLE
Add native flags

### ISSUE THREAD

**Issue by Dapid** [Qengineering/Install-OpenCV-Jetson-Nano#20]
Since we are building on the same hardware that is running, we can take full advantage of the compiler's knowledge of the CPU. I have succesfully built OpenCV adding the flags:

```
  -D CMAKE_CXX_FLAGS="-march=native -mtune=native" \
  -D CMAKE_C_FLAGS="-march=native -mtune=native"
```

I haven't benchmarked it, but on my experience with more complex CPUs, that usually gives me a 5-20% improvement.

Should I open a PR?

BTW: thanks for the scripts! It is great!

**Comment by Qengineering** [comment]
Thanks!
If you like to open a PR, be my guest.
Otherwise I will take care of it.
