### ISSUE TITLE
./OpenCV-4-8-0.sh error build with Makefile

### ISSUE THREAD

**Issue by thanhnt2410** [Qengineering/Install-OpenCV-Jetson-Nano#28]
Ubuntu 22.0.4
Jetson Orin nano
CUDA 12.2.140
cuDNN: 8.9.4.25
I used error when i run file setup. 
![image](https://github.com/user-attachments/assets/d8fef59a-b226-4b71-af68-7a533638c702)

**Comment by DarkblueShape** [comment]
Having the same issue. Have you happened to find a solution???

**Comment by thanhnt2410** [comment]
> Having the same issue. Have you happened to find a solution???

Hi DarkblueShape, I fixed it. The error by data type.
Follow and fix it at: https://github.com/opencv/opencv/issues/23893#issuecomment-1631143736
