### ISSUE TITLE
why I build opencv in virtualenv it always build for python2

### ISSUE THREAD

**Issue by hmnghia23** [Qengineering/Install-OpenCV-Jetson-Nano#4]

**Comment by Qengineering** [comment]
Your virtual environment is linked to a python version, which is given during the setup of the environment. In your case python2. If you want to use python3 besides python2, please google for hints and tips.
For instance this link on [stackoverflow](https://stackoverflow.com/questions/1534210/use-different-python-version-with-virtualenv/39713544#39713544).
